apiVersion: v1
kind: Secret
metadata:
  name: pkcs12-pass
data:
  password: c3VwZXJzZWNyZXQ=
type: Opaque
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-mutating-webhook
  annotations:
    cert-manager.io/inject-ca-from: default/sample-pod-mutating-webhook
webhooks:
  - name: sample.mutating.webhook
    clientConfig:
      service:
        name: pod-mutating-hook
        namespace: default
        path: "/mutate"
    rules:
      - operations: ["UPDATE","CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: [ "v1" ]
    sideEffects: None
    timeoutSeconds: 5
    failurePolicy: Ignore
